### PR TITLE
Country label move above text area

### PR DESCRIPTION
**Pull request by choiwa**

### CODE REVIEW

**Comment by iviondayjr** [comment]
image

Looks great!

**Comment by iviondayjr** [comment]
Tiny change, line 15 in Broadcast.jsx should be className

**Comment by rvrita** [comment]
Agree, looks great just fix that typo before merging :)

**Review by rvrita — APPROVED** [review]

**Comment by choiwa** [comment]
@iviondayjr @rvrita please review? The className supposed to be removed.

**Pull request merged**
